import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import ShowData from './ShowData';

const Skill = () => {

    const initialState = [
        {id: 1, title: "JavaSE"},
        {id: 2, title: "JavaEE"}]
    const [skills, setSkills ] = useState(initialState);

    const {register, handleSubmit, formState: {errors}} = useForm();

    const saveData = (data) => {

        console.log("Data: ", data);
        //add the data (title input) to the array skills
        const idManual= 3; //hardcoded data
        const id = Math.random().toString().substring(2,5); //random generated data
        //but if this is connected with backend app, we don't need to create id -> id is autogenerated in DB

        const title = data.title;
        const newObject = {id, title};
        skills.push(newObject); // push is used to add an element as last element of array
        console.log("Skills: ",skills);
    }
    

    return (
        <>
        <ShowData skills = {skills}/>

        <br/>

        <form onSubmit={handleSubmit(saveData)}>
            <div className='row'>
                <div className='col'>
                    <input type="text" className='form-control'{...register("title", {required: true})} placeholder="Please enter Title...."/>
                    {errors.title && errors.title.type === "required" && (
                        <span className='text-danger'>Title is required</span>
                    )}
                </div>
                <div className='col'>
                    <button type='submit' className='btn btn-success'>+</button>
                </div>

            </div>

        </form>
        </>

    );
};

export default Skill;